[package]
name = "waynest-protocols"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bitflags = { version = "2.9.4", features = ["std"] }
futures-core = "0.3.31"
futures-sink = "0.3.31"
waynest = { version = "0.0.26", path = "../core" }

[features]
stable = []
staging = []
unstable = []
wlr = []
plasma = []
weston = []
cosmic = ["wlr"]
frog = []
ivi = []
hyprland = []
mesa = []
treeland = []
