[package]
name = "waynest-protocols"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]

[features]
stable = []
staging = []
unstable = []
wlr = []
plasma = []
weston = []
cosmic = ["wlr"]
frog = []
ivi = []
hyprland = []
mesa = []
treeland = []
