[package]
name = "waynest-gen"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Codegen glue for waynest"
readme = "../README.md"
documentation = "https://docs.rs/waynest-gen"
repository.workspace = true
include = ["src/**/*.rs", "../README.md", "../LICENSE"]

[features]
bin = [
    "dep:anyhow",
    "dep:clap",
    "dep:tracing-subscriber",
    "dep:rayon",
    "dep:indexmap",
]

[dependencies]
thiserror = "2.0.7"
heck = "0.5.0"
proc-macro2 = { version = "1.0.92", default-features = false }
quick-xml = { version = "0.37.1", features = ["serialize", "overlapped-lists"] }
quote = { version = "1.0.37", default-features = false }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tracing = "0.1.41"

# Binary only deps
anyhow = { version = "1.0.94", optional = true }
clap = { version = "4.5.23", optional = true, features = ["derive"] }
tracing-subscriber = { version = "0.3.19", optional = true, features = [
    "env-filter",
] }
rayon = { version = "1.10.0", optional = true }
indexmap = { version = "2.7.0", optional = true, features = ["serde"] }

[[bin]]
name = "waynest-gen"
required-features = ["bin"]
