[package]
name = "waynest-gen"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Codegen glue for waynest"
readme = "../README.md"
documentation = "https://docs.rs/waynest-gen"
repository.workspace = true
include = ["src/**/*.rs", "../README.md", "../LICENSE"]

[features]
bin = [
    "dep:anyhow",
    "dep:clap",
    "dep:tracing-subscriber",
    "dep:rayon",
    "dep:indexmap",
]

[dependencies]
thiserror = "2.0.16"
heck = "0.5.0"
proc-macro2 = { version = "1.0.101", default-features = false }
quick-xml = { version = "0.38.3", features = ["serialize", "overlapped-lists"] }
quote = { version = "1.0.40", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tracing = "0.1.41"

# Binary only deps
anyhow = { version = "1.0.99", optional = true }
clap = { version = "4.5.47", optional = true, features = ["derive"] }
tracing-subscriber = { version = "0.3.20", optional = true, features = [
    "env-filter",
] }
rayon = { version = "1.11.0", optional = true }
indexmap = { version = "2.11.1", optional = true, features = ["serde"] }

[[bin]]
name = "waynest-gen"
required-features = ["bin"]
