[package]
name = "gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
heck = "0.5.0"
quick-xml = { version = "0.33.0", features = ["serialize", "overlapped-lists"] }
serde = { version = "1.0.203", features = ["derive"] }
