[package]
name = "waynest-gen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
heck = "0.5.0"
proc-macro2 = { version = "1.0.86", default-features = false }
quick-xml = { version = "0.36.1", features = ["serialize", "overlapped-lists"] }
quote = { version = "1.0.37", default-features = false }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
