[package]
name = "waynest-gen"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
description = "Codegen glue for waynest"
readme = "../README.md"
documentation = "https://docs.rs/waynest"
repository = "https://github.com/verdiwm/waynest"
include = ["src/**/*.rs", "../README.md", "../LICENSE"]

[features]
bin = ["dep:anyhow", "dep:clap", "dep:tracing-subscriber"]

[dependencies]
thiserror = "1.0.64"
heck = "0.5.0"
proc-macro2 = { version = "1.0.86", default-features = false }
quick-xml = { version = "0.36.2", features = ["serialize", "overlapped-lists"] }
quote = { version = "1.0.37", default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tracing = "0.1.40"

# Binary only deps
anyhow = { version = "1.0.89", optional = true }
clap = { version = "4.5.18", optional = true, features = ["derive"] }
tracing-subscriber = { version = "0.3.18", optional = true, features = [
    "env-filter",
] }

[[bin]]
name = "waynest-gen"
required-features = ["bin"]
