mod plasma {
    mod appmenu {}
    mod blur {}
    mod contrast {}
    mod dpms {}
    mod fake_input {}
    mod fullscreen_shell {}
    mod idle {}
    mod kde_external_brightness_v1 {}
    mod kde_lockscreen_overlay_v1 {}
    mod kde_output_device_v2 {}
    mod kde_output_management_v2 {}
    mod kde_output_order_v1 {}
    mod kde_primary_output_v1 {}
    mod kde_screen_edge_v1 {}
    mod keystate {}
    mod org_kde_plasma_virtual_desktop {}
    mod outputmanagement {}
    mod org_kde_kwin_outputdevice {}
    mod plasma_shell {}
    mod plasma_window_management {}
    mod remote_access {}
    mod server_decoration_palette {}
    mod server_decoration {}
    mod shadow {}
    mod slide {}
    mod surface_extension {}
    mod text_input_unstable_v2 {}
    mod text {}
    mod wl_eglstream_controller {}
    mod zkde_screencast_unstable_v1 {}
}
