mod staging {
    mod alpha_modifier_v1 {}
    mod color_management_v1 {}
    mod color_representation_v1 {}
    mod commit_timing_v1 {}
    mod content_type_v1 {}
    mod cursor_shape_v1 {}
    mod drm_lease_v1 {}
    mod ext_background_effect_v1 {}
    mod ext_data_control_v1 {}
    mod ext_foreign_toplevel_list_v1 {}
    mod ext_idle_notify_v1 {}
    mod ext_image_capture_source_v1 {}
    mod ext_image_copy_capture_v1 {}
    mod ext_session_lock_v1 {}
    mod ext_transient_seat_v1 {}
    mod ext_workspace_v1 {}
    mod fifo_v1 {}
    mod fractional_scale_v1 {}
    mod linux_drm_syncobj_v1 {}
    mod pointer_warp_v1 {}
    mod security_context_v1 {}
    mod single_pixel_buffer_v1 {}
    mod tearing_control_v1 {}
    mod xdg_activation_v1 {}
    mod xdg_dialog_v1 {}
    mod xdg_system_bell_v1 {}
    mod xdg_toplevel_drag_v1 {}
    mod xdg_toplevel_icon_v1 {}
    mod xdg_toplevel_tag_v1 {}
    mod xwayland_shell_v1 {}
}
