#![allow(unused)]
#![allow(async_fn_in_trait)]
pub mod wayland {}
pub mod linux_dmabuf_v1 {}
pub mod presentation_time {}
pub mod tablet_v2 {}
pub mod viewporter {}
pub mod xdg_shell {}
pub mod alpha_modifier_v1 {}
pub mod content_type_v1 {}
pub mod cursor_shape_v1 {}
pub mod drm_lease_v1 {}
pub mod ext_foreign_toplevel_list_v1 {}
pub mod ext_idle_notify_v1 {}
pub mod ext_session_lock_v1 {}
pub mod ext_transient_seat_v1 {}
pub mod fractional_scale_v1 {}
pub mod linux_drm_syncobj_v1 {}
pub mod security_context_v1 {}
pub mod single_pixel_buffer_v1 {}
pub mod tearing_control_v1 {}
pub mod xdg_activation_v1 {}
pub mod xdg_dialog_v1 {}
pub mod xdg_toplevel_drag_v1 {}
pub mod xwayland_shell_v1 {}
pub mod fullscreen_shell_unstable_v1 {}
pub mod idle_inhibit_unstable_v1 {}
pub mod input_method_unstable_v1 {}
pub mod input_timestamps_unstable_v1 {}
pub mod keyboard_shortcuts_inhibit_unstable_v1 {}
pub mod linux_dmabuf_unstable_v1 {}
pub mod zwp_linux_explicit_synchronization_unstable_v1 {}
pub mod pointer_constraints_unstable_v1 {}
pub mod pointer_gestures_unstable_v1 {}
pub mod wp_primary_selection_unstable_v1 {}
pub mod relative_pointer_unstable_v1 {}
pub mod tablet_unstable_v1 {}
pub mod tablet_unstable_v2 {}
pub mod text_input_unstable_v1 {}
pub mod text_input_unstable_v3 {}
pub mod xdg_decoration_unstable_v1 {}
pub mod xdg_foreign_unstable_v1 {}
pub mod xdg_foreign_unstable_v2 {}
pub mod xdg_output_unstable_v1 {}
pub mod xdg_shell_unstable_v5 {}
pub mod xdg_shell_unstable_v6 {}
pub mod wlr_data_control_unstable_v1 {}
pub mod wlr_export_dmabuf_unstable_v1 {}
pub mod wlr_foreign_toplevel_management_unstable_v1 {}
pub mod wlr_gamma_control_unstable_v1 {}
pub mod wlr_input_inhibit_unstable_v1 {}
pub mod wlr_layer_shell_unstable_v1 {}
pub mod wlr_output_management_unstable_v1 {}
pub mod wlr_output_power_management_unstable_v1 {}
pub mod wlr_screencopy_unstable_v1 {}
pub mod wlr_virtual_pointer_unstable_v1 {}
